default:
  image: registry.gitlab.com/40hz/docker-images/remix:6.1.9

stages:
  - check
  - test

format-check:
  stage: check
  script:
    - echo "Checking code formatting..."
    - find test include examples -name '*.h' -o -name '*.hpp' -o -name '*.c' -o -name '*.cpp' | xargs clang-format-16 -n -Werror


unit-test:
  stage: test
  script:
    - pio test -e native